import Movie from '../models/Movie.js';

let movies = [
  {
    rank: '1',
    title: 'The Shawshank Redemption',
    fullTitle: 'The Shawshank Redemption (1994)',
    year: '1994',
    image:
      'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Frank Darabont (dir.), Tim Robbins, Morgan Freeman',
    imDbRating: '9.2',
    imDbRatingCount: '2560641',
  },
  {
    rank: '2',
    title: 'The Godfather',
    fullTitle: 'The Godfather (1972)',
    year: '1972',
    image:
      'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Francis Ford Coppola (dir.), Marlon Brando, Al Pacino',
    imDbRating: '9.2',
    imDbRatingCount: '1762558',
  },
  {
    rank: '3',
    title: 'The Dark Knight',
    fullTitle: 'The Dark Knight (2008)',
    year: '2008',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Christopher Nolan (dir.), Christian Bale, Heath Ledger',
    imDbRating: '9.0',
    imDbRatingCount: '2521055',
  },
  {
    rank: '4',
    title: 'The Godfather: Part II',
    fullTitle: 'The Godfather: Part II (1974)',
    year: '1974',
    image:
      'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Francis Ford Coppola (dir.), Al Pacino, Robert De Niro',
    imDbRating: '9.0',
    imDbRatingCount: '1220490',
  },
  {
    rank: '5',
    title: '12 Angry Men',
    fullTitle: '12 Angry Men (1957)',
    year: '1957',
    image:
      'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '9.0',
    imDbRatingCount: '756468',
  },
  {
    rank: '6',
    title: "Schindler's List",
    fullTitle: "Schindler's List (1993)",
    year: '1993',
    image:
      'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes',
    imDbRating: '8.9',
    imDbRatingCount: '1305645',
  },
  {
    rank: '7',
    title: 'The Lord of the Rings: The Return of the King',
    fullTitle: 'The Lord of the Rings: The Return of the King (2003)',
    year: '2003',
    image:
      'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Peter Jackson (dir.), Elijah Wood, Viggo Mortensen',
    imDbRating: '8.9',
    imDbRatingCount: '1763164',
  },
  {
    rank: '8',
    title: 'Pulp Fiction',
    fullTitle: 'Pulp Fiction (1994)',
    year: '1994',
    image:
      'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Quentin Tarantino (dir.), John Travolta, Uma Thurman',
    imDbRating: '8.9',
    imDbRatingCount: '1967023',
  },
  {
    rank: '9',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    fullTitle: 'The Lord of the Rings: The Fellowship of the Ring (2001)',
    year: '2001',
    image:
      'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Peter Jackson (dir.), Elijah Wood, Ian McKellen',
    imDbRating: '8.8',
    imDbRatingCount: '1785022',
  },
  {
    rank: '10',
    title: 'The Good, the Bad and the Ugly',
    fullTitle: 'The Good, the Bad and the Ugly (1966)',
    year: '1966',
    image:
      'https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Sergio Leone (dir.), Clint Eastwood, Eli Wallach',
    imDbRating: '8.8',
    imDbRatingCount: '737327',
  },
  {
    rank: '11',
    title: 'Forrest Gump',
    fullTitle: 'Forrest Gump (1994)',
    year: '1994',
    image:
      'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Robert Zemeckis (dir.), Tom Hanks, Robin Wright',
    imDbRating: '8.8',
    imDbRatingCount: '1975642',
  },
  {
    rank: '12',
    title: 'Fight Club',
    fullTitle: 'Fight Club (1999)',
    year: '1999',
    image:
      'https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '8.8',
    imDbRatingCount: '2015325',
  },
  {
    rank: '13',
    title: 'Inception',
    fullTitle: 'Inception (2010)',
    year: '2010',
    image:
      'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt',
    imDbRating: '8.7',
    imDbRatingCount: '2248175',
  },
  {
    rank: '14',
    title: 'The Lord of the Rings: The Two Towers',
    fullTitle: 'The Lord of the Rings: The Two Towers (2002)',
    year: '2002',
    image:
      'https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Peter Jackson (dir.), Elijah Wood, Ian McKellen',
    imDbRating: '8.7',
    imDbRatingCount: '1592925',
  },
  {
    rank: '15',
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    fullTitle: 'Star Wars: Episode V - The Empire Strikes Back (1980)',
    year: '1980',
    image:
      'https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Irvin Kershner (dir.), Mark Hamill, Harrison Ford',
    imDbRating: '8.7',
    imDbRatingCount: '1239944',
  },
  {
    rank: '16',
    title: 'The Matrix',
    fullTitle: 'The Matrix (1999)',
    year: '1999',
    image:
      'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne',
    imDbRating: '8.7',
    imDbRatingCount: '1844782',
  },
  {
    rank: '17',
    title: 'Goodfellas',
    fullTitle: 'Goodfellas (1990)',
    year: '1990',
    image:
      'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Martin Scorsese (dir.), Robert De Niro, Ray Liotta',
    imDbRating: '8.7',
    imDbRatingCount: '1105602',
  },
  {
    rank: '18',
    title: "One Flew Over the Cuckoo's Nest",
    fullTitle: "One Flew Over the Cuckoo's Nest (1975)",
    year: '1975',
    image:
      'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Milos Forman (dir.), Jack Nicholson, Louise Fletcher',
    imDbRating: '8.6',
    imDbRatingCount: '976612',
  },
  {
    rank: '19',
    title: 'Se7en',
    fullTitle: 'Se7en (1995)',
    year: '1995',
    image:
      'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '8.6',
    imDbRatingCount: '1570202',
  },
  {
    rank: '20',
    title: 'Seven Samurai',
    fullTitle: 'Seven Samurai (1954)',
    year: '1954',
    image:
      'https://m.media-amazon.com/images/M/MV5BOWE4ZDdhNmMtNzE5ZC00NzExLTlhNGMtY2ZhYjYzODEzODA1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura',
    imDbRating: '8.6',
    imDbRatingCount: '336824',
  },
  {
    rank: '21',
    title: "It's a Wonderful Life",
    fullTitle: "It's a Wonderful Life (1946)",
    year: '1946',
    image:
      'https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Frank Capra (dir.), James Stewart, Donna Reed',
    imDbRating: '8.6',
    imDbRatingCount: '441638',
  },
  {
    rank: '22',
    title: 'The Silence of the Lambs',
    fullTitle: 'The Silence of the Lambs (1991)',
    year: '1991',
    image:
      'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins',
    imDbRating: '8.6',
    imDbRatingCount: '1373801',
  },
  {
    rank: '23',
    title: 'Saving Private Ryan',
    fullTitle: 'Saving Private Ryan (1998)',
    year: '1998',
    image:
      'https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Steven Spielberg (dir.), Tom Hanks, Matt Damon',
    imDbRating: '8.6',
    imDbRatingCount: '1334712',
  },
  {
    rank: '24',
    title: 'City of God',
    fullTitle: 'City of God (2002)',
    year: '2002',
    image:
      'https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTZlMWQzNzI5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino',
    imDbRating: '8.6',
    imDbRatingCount: '736969',
  },
  {
    rank: '25',
    title: 'Life Is Beautiful',
    fullTitle: 'Life Is Beautiful (1997)',
    year: '1997',
    image:
      'https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi',
    imDbRating: '8.6',
    imDbRatingCount: '671429',
  },
  {
    rank: '26',
    title: 'The Green Mile',
    fullTitle: 'The Green Mile (1999)',
    year: '1999',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan',
    imDbRating: '8.6',
    imDbRatingCount: '1245211',
  },
  {
    rank: '27',
    title: 'Star Wars',
    fullTitle: 'Star Wars (1977)',
    year: '1977',
    image:
      'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'George Lucas (dir.), Mark Hamill, Harrison Ford',
    imDbRating: '8.6',
    imDbRatingCount: '1311433',
  },
  {
    rank: '28',
    title: 'Interstellar',
    fullTitle: 'Interstellar (2014)',
    year: '2014',
    image:
      'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway',
    imDbRating: '8.6',
    imDbRatingCount: '1705110',
  },
  {
    rank: '29',
    title: 'Terminator 2: Judgment Day',
    fullTitle: 'Terminator 2: Judgment Day (1991)',
    year: '1991',
    image:
      'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton',
    imDbRating: '8.5',
    imDbRatingCount: '1060433',
  },
  {
    rank: '30',
    title: 'Back to the Future',
    fullTitle: 'Back to the Future (1985)',
    year: '1985',
    image:
      'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd',
    imDbRating: '8.5',
    imDbRatingCount: '1149859',
  },
  {
    rank: '31',
    title: 'Spirited Away',
    fullTitle: 'Spirited Away (2001)',
    year: '2001',
    image:
      'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette',
    imDbRating: '8.5',
    imDbRatingCount: '723352',
  },
  {
    rank: '32',
    title: 'Psycho',
    fullTitle: 'Psycho (1960)',
    year: '1960',
    image:
      'https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh',
    imDbRating: '8.5',
    imDbRatingCount: '648365',
  },
  {
    rank: '33',
    title: 'Léon: The Professional',
    fullTitle: 'Léon: The Professional (1994)',
    year: '1994',
    image:
      'https://m.media-amazon.com/images/M/MV5BODllNWE0MmEtYjUwZi00ZjY3LThmNmQtZjZlMjI2YTZjYmQ0XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Luc Besson (dir.), Jean Reno, Gary Oldman',
    imDbRating: '8.5',
    imDbRatingCount: '1117041',
  },
  {
    rank: '34',
    title: 'The Pianist',
    fullTitle: 'The Pianist (2002)',
    year: '2002',
    image:
      'https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY176_CR0,0,128,176_AL_.jpg',
    crew: 'Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann',
    imDbRating: '8.5',
    imDbRatingCount: '798059',
  },
  {
    rank: '35',
    title: 'Parasite',
    fullTitle: 'Parasite (2019)',
    year: '2019',
    image:
      'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Bong Joon Ho (dir.), Kang-ho Song, Sun-kyun Lee',
    imDbRating: '8.5',
    imDbRatingCount: '726482',
  },
  {
    rank: '36',
    title: 'The Lion King',
    fullTitle: 'The Lion King (1994)',
    year: '1994',
    image:
      'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Roger Allers (dir.), Matthew Broderick, Jeremy Irons',
    imDbRating: '8.5',
    imDbRatingCount: '1014958',
  },
  {
    rank: '37',
    title: 'Gladiator',
    fullTitle: 'Gladiator (2000)',
    year: '2000',
    image:
      'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '8.5',
    imDbRatingCount: '1442052',
  },
  {
    rank: '38',
    title: 'American History X',
    fullTitle: 'American History X (1998)',
    year: '1998',
    image:
      'https://m.media-amazon.com/images/M/MV5BZTJhN2FkYWEtMGI0My00YWM4LWI2MjAtM2UwNjY4MTI2ZTQyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Tony Kaye (dir.), Edward Norton, Edward Furlong',
    imDbRating: '8.5',
    imDbRatingCount: '1089870',
  },
  {
    rank: '39',
    title: 'The Usual Suspects',
    fullTitle: 'The Usual Suspects (1995)',
    year: '1995',
    image:
      'https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne',
    imDbRating: '8.5',
    imDbRatingCount: '1054032',
  },
  {
    rank: '40',
    title: 'The Departed',
    fullTitle: 'The Departed (2006)',
    year: '2006',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon',
    imDbRating: '8.5',
    imDbRatingCount: '1275758',
  },
  {
    rank: '41',
    title: 'The Prestige',
    fullTitle: 'The Prestige (2006)',
    year: '2006',
    image:
      'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Christopher Nolan (dir.), Christian Bale, Hugh Jackman',
    imDbRating: '8.5',
    imDbRatingCount: '1283414',
  },
  {
    rank: '42',
    title: 'Casablanca',
    fullTitle: 'Casablanca (1942)',
    year: '1942',
    image:
      'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '8.5',
    imDbRatingCount: '555966',
  },
  {
    rank: '43',
    title: 'Whiplash',
    fullTitle: 'Whiplash (2014)',
    year: '2014',
    image:
      'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Damien Chazelle (dir.), Miles Teller, J.K. Simmons',
    imDbRating: '8.5',
    imDbRatingCount: '797769',
  },
  {
    rank: '44',
    title: 'The Intouchables',
    fullTitle: 'The Intouchables (2011)',
    year: '2011',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Olivier Nakache (dir.), François Cluzet, Omar Sy',
    imDbRating: '8.5',
    imDbRatingCount: '823952',
  },
  {
    rank: '45',
    title: 'Modern Times',
    fullTitle: 'Modern Times (1936)',
    year: '1936',
    image:
      'https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard',
    imDbRating: '8.5',
    imDbRatingCount: '235458',
  },
  {
    rank: '46',
    title: 'Once Upon a Time in the West',
    fullTitle: 'Once Upon a Time in the West (1968)',
    year: '1968',
    image:
      'https://m.media-amazon.com/images/M/MV5BZGI5MjBmYzYtMzJhZi00NGI1LTk3MzItYjBjMzcxM2U3MDdiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Sergio Leone (dir.), Henry Fonda, Charles Bronson',
    imDbRating: '8.5',
    imDbRatingCount: '321436',
  },
  {
    rank: '47',
    title: 'Hara-Kiri',
    fullTitle: 'Hara-Kiri (1962)',
    year: '1962',
    image:
      'https://m.media-amazon.com/images/M/MV5BYjBmYTQ1NjItZWU5MS00YjI0LTg2OTYtYmFkN2JkMmNiNWVkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_UY176_CR0,0,128,176_AL_.jpg',
    crew: 'Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama',
    imDbRating: '8.5',
    imDbRatingCount: '52914',
  },
  {
    rank: '48',
    title: 'Grave of the Fireflies',
    fullTitle: 'Grave of the Fireflies (1988)',
    year: '1988',
    image:
      'https://m.media-amazon.com/images/M/MV5BZmY2NjUzNDQtNTgxNC00M2Q4LTljOWQtMjNjNDBjNWUxNmJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi',
    imDbRating: '8.5',
    imDbRatingCount: '263537',
  },
  {
    rank: '49',
    title: 'Alien',
    fullTitle: 'Alien (1979)',
    year: '1979',
    image:
      'https://m.media-amazon.com/images/M/MV5BMmQ2MmU3NzktZjAxOC00ZDZhLTk4YzEtMDMyMzcxY2IwMDAyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '8.4',
    imDbRatingCount: '846635',
  },
  {
    rank: '50',
    title: 'Rear Window',
    fullTitle: 'Rear Window (1954)',
    year: '1954',
    image:
      'https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Alfred Hitchcock (dir.), James Stewart, Grace Kelly',
    imDbRating: '8.4',
    imDbRatingCount: '477346',
  },
  {
    rank: '51',
    title: 'City Lights',
    fullTitle: 'City Lights (1931)',
    year: '1931',
    image:
      'https://m.media-amazon.com/images/M/MV5BY2I4MmM1N2EtM2YzOS00OWUzLTkzYzctNDc5NDg2N2IyODJmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill',
    imDbRating: '8.4',
    imDbRatingCount: '180439',
  },
  {
    rank: '52',
    title: 'Memento',
    fullTitle: 'Memento (2000)',
    year: '2000',
    image:
      'https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss',
    imDbRating: '8.4',
    imDbRatingCount: '1198862',
  },
  {
    rank: '53',
    title: 'Apocalypse Now',
    fullTitle: 'Apocalypse Now (1979)',
    year: '1979',
    image:
      'https://m.media-amazon.com/images/M/MV5BMDdhODg0MjYtYzBiOS00ZmI5LWEwZGYtZDEyNDU4MmQyNzFkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando',
    imDbRating: '8.4',
    imDbRatingCount: '646079',
  },
  {
    rank: '54',
    title: 'Cinema Paradiso',
    fullTitle: 'Cinema Paradiso (1988)',
    year: '1988',
    image:
      'https://m.media-amazon.com/images/M/MV5BM2FhYjEyYmYtMDI1Yy00YTdlLWI2NWQtYmEzNzAxOGY1NjY2XkEyXkFqcGdeQXVyNTA3NTIyNDg@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale',
    imDbRating: '8.4',
    imDbRatingCount: '252534',
  },
  {
    rank: '55',
    year: '1981',
    image:
      'https://m.media-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Steven Spielberg (dir.), Harrison Ford, Karen Allen',
    imDbRating: '8.4',
    imDbRatingCount: '937703',
  },
  {
    rank: '56',
    title: 'Django Unchained',
    fullTitle: 'Django Unchained (2012)',
    year: '2012',
    image:
      'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz',
    imDbRating: '8.4',
    imDbRatingCount: '1479810',
  },
  {
    rank: '57',
    title: 'WALL·E',
    fullTitle: 'WALL·E (2008)',
    year: '2008',
    image:
      'https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Andrew Stanton (dir.), Ben Burtt, Elissa Knight',
    imDbRating: '8.4',
    imDbRatingCount: '1074459',
  },
  {
    rank: '58',
    year: '2021',
    image:
      'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Jon Watts (dir.), Tom Holland, Zendaya',
    imDbRating: '8.4',
    imDbRatingCount: '524942',
  },
  {
    rank: '59',
    title: 'The Lives of Others',
    fullTitle: 'The Lives of Others (2006)',
    year: '2006',
    image:
      'https://m.media-amazon.com/images/M/MV5BOTQyZGFjNWMtYWFiYy00OWU1LTlhMjAtYTBiNmU5NjJiNTAzXkEyXkFqcGdeQXVyMTI3ODAyMzE2._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck',
    imDbRating: '8.4',
    imDbRatingCount: '380938',
  },
  {
    rank: '60',
    title: 'Sunset Blvd.',
    fullTitle: 'Sunset Blvd. (1950)',
    year: '1950',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTU0NTkyNzYwMF5BMl5BanBnXkFtZTgwMDU0NDk5MTI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Billy Wilder (dir.), William Holden, Gloria Swanson',
    imDbRating: '8.4',
    imDbRatingCount: '216118',
  },
  {
    rank: '61',
    title: 'The Shining',
    fullTitle: 'The Shining (1980)',
    year: '1980',
    image:
      'https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall',
    imDbRating: '8.4',
    imDbRatingCount: '975921',
  },
  {
    rank: '62',
    title: 'Paths of Glory',
    fullTitle: 'Paths of Glory (1957)',
    year: '1957',
    image:
      'https://m.media-amazon.com/images/M/MV5BNjViMmRkOTEtM2ViOS00ODg0LWJhYWEtNTBlOGQxNDczOGY3XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker',
    imDbRating: '8.4',
    imDbRatingCount: '191890',
  },
  {
    rank: '63',
    title: 'The Great Dictator',
    fullTitle: 'The Great Dictator (1940)',
    year: '1940',
    image:
      'https://m.media-amazon.com/images/M/MV5BMmExYWJjNTktNGUyZS00ODhmLTkxYzAtNWIzOGEyMGNiMmUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard',
    imDbRating: '8.4',
    imDbRatingCount: '218665',
  },
  {
    rank: '64',
    title: 'Avengers: Infinity War',
    fullTitle: 'Avengers: Infinity War (2018)',
    year: '2018',
    image:
      'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth',
    imDbRating: '8.4',
    imDbRatingCount: '992734',
  },
  {
    rank: '65',
    title: 'Witness for the Prosecution',
    fullTitle: 'Witness for the Prosecution (1957)',
    year: '1957',
    image:
      'https://m.media-amazon.com/images/M/MV5BNDQwODU5OWYtNDcyNi00MDQ1LThiOGMtZDkwNWJiM2Y3MDg0XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Billy Wilder (dir.), Tyrone Power, Marlene Dietrich',
    imDbRating: '8.4',
    imDbRatingCount: '120945',
  },
  {
    rank: '66',
    title: 'Aliens',
    fullTitle: 'Aliens (1986)',
    year: '1986',
    image:
      'https://m.media-amazon.com/images/M/MV5BZGU2OGY5ZTYtMWNhYy00NjZiLWI0NjUtZmNhY2JhNDRmODU3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'James Cameron (dir.), Sigourney Weaver, Michael Biehn',
    imDbRating: '8.4',
    imDbRatingCount: '694898',
  },
  {
    rank: '67',
    title: 'American Beauty',
    fullTitle: 'American Beauty (1999)',
    year: '1999',
    image:
      'https://m.media-amazon.com/images/M/MV5BNTBmZWJkNjctNDhiNC00MGE2LWEwOTctZTk5OGVhMWMyNmVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Sam Mendes (dir.), Kevin Spacey, Annette Bening',
    imDbRating: '8.3',
    imDbRatingCount: '1125828',
  },
  {
    rank: '68',
    title: 'The Dark Knight Rises',
    fullTitle: 'The Dark Knight Rises (2012)',
    year: '2012',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Christopher Nolan (dir.), Christian Bale, Tom Hardy',
    imDbRating: '8.3',
    imDbRatingCount: '1632653',
  },
  {
    rank: '69',
    title:
      'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    fullTitle:
      'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)',
    year: '1964',
    image:
      'https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Stanley Kubrick (dir.), Peter Sellers, George C. Scott',
    imDbRating: '8.3',
    imDbRatingCount: '477115',
  },
  {
    rank: '70',
    title: 'Joker',
    fullTitle: 'Joker (2019)',
    year: '2019',
    image:
      'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro',
    imDbRating: '8.3',
    imDbRatingCount: '1162144',
  },
  {
    rank: '71',
    year: '2018',
    image:
      'https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Bob Persichetti (dir.), Shameik Moore, Jake Johnson',
    imDbRating: '8.3',
    imDbRatingCount: '477620',
  },
  {
    rank: '72',
    title: 'Old Boy',
    fullTitle: 'Old Boy (2003)',
    year: '2003',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Park Chan-wook (dir.), Choi Min-sik, Yoo Ji-Tae',
    imDbRating: '8.3',
    imDbRatingCount: '557375',
  },
  {
    rank: '73',
    title: 'Braveheart',
    fullTitle: 'Braveheart (1995)',
    year: '1995',
    image:
      'https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Mel Gibson (dir.), Mel Gibson, Sophie Marceau',
    imDbRating: '8.3',
    imDbRatingCount: '1010568',
  },
  {
    rank: '74',
    title: 'Toy Story',
    fullTitle: 'Toy Story (1995)',
    year: '1995',
    image:
      'https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'John Lasseter (dir.), Tom Hanks, Tim Allen',
    imDbRating: '8.3',
    imDbRatingCount: '955110',
  },
  {
    rank: '75',
    title: 'Amadeus',
    fullTitle: 'Amadeus (1984)',
    year: '1984',
    image:
      'https://m.media-amazon.com/images/M/MV5BNWJlNzUzNGMtYTAwMS00ZjI2LWFmNWQtODcxNWUxODA5YmU1XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Milos Forman (dir.), F. Murray Abraham, Tom Hulce',
    imDbRating: '8.3',
    imDbRatingCount: '391049',
  },
  {
    rank: '76',
    title: 'Coco',
    fullTitle: 'Coco (2017)',
    year: '2017',
    image:
      'https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal',
    imDbRating: '8.3',
    imDbRatingCount: '467728',
  },
  {
    rank: '77',
    title: 'Inglourious Basterds',
    fullTitle: 'Inglourious Basterds (2009)',
    year: '2009',
    image:
      'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Quentin Tarantino (dir.), Brad Pitt, Diane Kruger',
    imDbRating: '8.3',
    imDbRatingCount: '1380717',
  },
  {
    rank: '78',
    title: 'The Boat',
    fullTitle: 'The Boat (1981)',
    year: '1981',
    image:
      'https://m.media-amazon.com/images/M/MV5BOGZhZDIzNWMtNjkxMS00MDQ1LThkMTYtZWQzYWU3MWMxMGU5XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer',
    imDbRating: '8.3',
    imDbRatingCount: '245706',
  },
  {
    rank: '79',
    title: 'Avengers: Endgame',
    fullTitle: 'Avengers: Endgame (2019)',
    year: '2019',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Anthony Russo (dir.), Robert Downey Jr., Chris Evans',
    imDbRating: '8.3',
    imDbRatingCount: '1026763',
  },
  {
    rank: '80',
    title: 'Princess Mononoke',
    fullTitle: 'Princess Mononoke (1997)',
    year: '1997',
    image:
      'https://m.media-amazon.com/images/M/MV5BNGIzY2IzODQtNThmMi00ZDE4LWI5YzAtNzNlZTM1ZjYyYjUyXkEyXkFqcGdeQXVyODEzNjM5OTQ@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '8.3',
    imDbRatingCount: '378113',
  },
  {
    rank: '81',
    title: 'Once Upon a Time in America',
    fullTitle: 'Once Upon a Time in America (1984)',
    year: '1984',
    image:
      'https://m.media-amazon.com/images/M/MV5BMGFkNWI4MTMtNGQ0OC00MWVmLTk3MTktOGYxN2Y2YWVkZWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Sergio Leone (dir.), Robert De Niro, James Woods',
    imDbRating: '8.3',
    imDbRatingCount: '339945',
  },
  {
    rank: '82',
    title: 'Good Will Hunting',
    fullTitle: 'Good Will Hunting (1997)',
    year: '1997',
    image:
      'https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Gus Van Sant (dir.), Robin Williams, Matt Damon',
    imDbRating: '8.3',
    imDbRatingCount: '929304',
  },
  {
    rank: '83',
    title: 'Toy Story 3',
    fullTitle: 'Toy Story 3 (2010)',
    year: '2010',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Lee Unkrich (dir.), Tom Hanks, Tim Allen',
    imDbRating: '8.3',
    imDbRatingCount: '807107',
  },
  {
    rank: '84',
    title: 'Requiem for a Dream',
    fullTitle: 'Requiem for a Dream (2000)',
    year: '2000',
    image:
      'https://m.media-amazon.com/images/M/MV5BOTdiNzJlOWUtNWMwNS00NmFlLWI0YTEtZmI3YjIzZWUyY2Y3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto',
    imDbRating: '8.3',
    imDbRatingCount: '814736',
  },
  {
    rank: '85',
    year: '2009',
    image:
      'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Rajkumar Hirani (dir.), Aamir Khan, Madhavan',
    imDbRating: '8.3',
    imDbRatingCount: '381581',
  },
  {
    rank: '86',
    title: 'Your Name.',
    fullTitle: 'Your Name. (2016)',
    year: '2016',
    image:
      'https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi',
    imDbRating: '8.3',
    imDbRatingCount: '244553',
  },
  {
    rank: '87',
    title: "Singin' in the Rain",
    fullTitle: "Singin' in the Rain (1952)",
    year: '1952',
    image:
      'https://m.media-amazon.com/images/M/MV5BZDRjNGViMjQtOThlMi00MTA3LThkYzQtNzJkYjBkMGE0YzE1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: "Stanley Donen (dir.), Gene Kelly, Donald O'Connor",
    imDbRating: '8.3',
    imDbRatingCount: '235083',
  },
  {
    rank: '88',
    title: 'Star Wars: Episode VI - Return of the Jedi',
    fullTitle: 'Star Wars: Episode VI - Return of the Jedi (1983)',
    year: '1983',
    image:
      'https://m.media-amazon.com/images/M/MV5BOWZlMjFiYzgtMTUzNC00Y2IzLTk1NTMtZmNhMTczNTk0ODk1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Richard Marquand (dir.), Mark Hamill, Harrison Ford',
    imDbRating: '8.3',
    imDbRatingCount: '1013447',
  },
  {
    rank: '89',
    title: 'Reservoir Dogs',
    fullTitle: 'Reservoir Dogs (1992)',
    year: '1992',
    image:
      'https://m.media-amazon.com/images/M/MV5BZmExNmEwYWItYmQzOS00YjA5LTk2MjktZjEyZDE1Y2QxNjA1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Quentin Tarantino (dir.), Harvey Keitel, Tim Roth',
    imDbRating: '8.3',
    imDbRatingCount: '983149',
  },
  {
    rank: '90',
    title: 'Eternal Sunshine of the Spotless Mind',
    fullTitle: 'Eternal Sunshine of the Spotless Mind (2004)',
    year: '2004',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Michel Gondry (dir.), Jim Carrey, Kate Winslet',
    imDbRating: '8.3',
    imDbRatingCount: '972896',
  },
  {
    rank: '91',
    title: '2001: A Space Odyssey',
    fullTitle: '2001: A Space Odyssey (1968)',
    year: '1968',
    image:
      'https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood',
    imDbRating: '8.3',
    imDbRatingCount: '646704',
  },
  {
    rank: '92',
    title: 'High and Low',
    fullTitle: 'High and Low (1963)',
    year: '1963',
    image:
      'https://m.media-amazon.com/images/M/MV5BOTI4NTNhZDMtMWNkZi00MTRmLWJmZDQtMmJkMGVmZTEzODlhXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada',
    imDbRating: '8.3',
    imDbRatingCount: '42081',
  },
  {
    rank: '93',
    title: 'Citizen Kane',
    fullTitle: 'Citizen Kane (1941)',
    year: '1941',
    image:
      'https://m.media-amazon.com/images/M/MV5BYjBiOTYxZWItMzdiZi00NjlkLWIzZTYtYmFhZjhiMTljOTdkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Orson Welles (dir.), Orson Welles, Joseph Cotten',
    imDbRating: '8.3',
    imDbRatingCount: '431752',
  },
  {
    rank: '94',
    title: 'Lawrence of Arabia',
    fullTitle: 'Lawrence of Arabia (1962)',
    year: '1962',
    image:
      'https://m.media-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '8.3',
    imDbRatingCount: '286054',
  },
  {
    rank: '95',
    title: 'Capernaum',
    fullTitle: 'Capernaum (2018)',
    year: '2018',
    image:
      'https://m.media-amazon.com/images/M/MV5BMmExNzU2ZWMtYzUwYi00YmM2LTkxZTQtNmVhNjY0NTMyMWI2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw',
    imDbRating: '8.3',
    imDbRatingCount: '82971',
  },
  {
    rank: '96',
    title: 'M',
    fullTitle: 'M (1931)',
    year: '1931',
    image:
      'https://m.media-amazon.com/images/M/MV5BODA4ODk3OTEzMF5BMl5BanBnXkFtZTgwMTQ2ODMwMzE@._V1_UX128_CR0,3,128,176_AL_.jpg',
    imDbRating: '8.3',
    imDbRatingCount: '154264',
  },
  {
    rank: '97',
    title: 'North by Northwest',
    fullTitle: 'North by Northwest (1959)',
    year: '1959',
    image:
      'https://m.media-amazon.com/images/M/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Alfred Hitchcock (dir.), Cary Grant, Eva Marie Saint',
    imDbRating: '8.3',
    imDbRatingCount: '319628',
  },
  {
    rank: '98',
    title: 'The Hunt',
    fullTitle: 'The Hunt (2012)',
    year: '2012',
    image:
      'https://m.media-amazon.com/images/M/MV5BMTg2NDg3ODg4NF5BMl5BanBnXkFtZTcwNzk3NTc3Nw@@._V1_UX128_CR0,1,128,176_AL_.jpg',
    crew: 'Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen',
    imDbRating: '8.3',
    imDbRatingCount: '316136',
  },
  {
    rank: '99',
    title: 'Vertigo',
    fullTitle: 'Vertigo (1958)',
    year: '1958',
    image:
      'https://m.media-amazon.com/images/M/MV5BYTE4ODEwZDUtNDFjOC00NjAxLWEzYTQtYTI1NGVmZmFlNjdiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Alfred Hitchcock (dir.), James Stewart, Kim Novak',
    imDbRating: '8.3',
    imDbRatingCount: '391918',
  },
  {
    rank: '100',
    title: 'Amélie',
    fullTitle: 'Amélie (2001)',
    year: '2001',
    image:
      'https://m.media-amazon.com/images/M/MV5BNDg4NjM1YjMtYmNhZC00MjM0LWFiZmYtNGY1YjA3MzZmODc5XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX128_CR0,3,128,176_AL_.jpg',
    crew: 'Jean-Pierre Jeunet (dir.), Audrey Tautou, Mathieu Kassovitz',
    imDbRating: '8.3',
    imDbRatingCount: '739064',
  },
];

movies = movies.map((movie) => ({
  ...movie,
  rank: +movie.rank,
  year: +movie.year,
  imDbRating: +movie.imDbRating,
  imDbRatingCount: +movie.imDbRatingCount,
  isLiked: false,
  isTouched: false,
  rate: 0,
}));

Movie.insertMany(movies);
